// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: prime/primepb/prime.proto

package primepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Prime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *Prime) Reset() {
	*x = Prime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prime_primepb_prime_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Prime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prime) ProtoMessage() {}

func (x *Prime) ProtoReflect() protoreflect.Message {
	mi := &file_prime_primepb_prime_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prime.ProtoReflect.Descriptor instead.
func (*Prime) Descriptor() ([]byte, []int) {
	return file_prime_primepb_prime_proto_rawDescGZIP(), []int{0}
}

func (x *Prime) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dividends int32 `protobuf:"varint,1,opt,name=dividends,proto3" json:"dividends,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prime_primepb_prime_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_prime_primepb_prime_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_prime_primepb_prime_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetDividends() int32 {
	if x != nil {
		return x.Dividends
	}
	return 0
}

var File_prime_primepb_prime_proto protoreflect.FileDescriptor

var file_prime_primepb_prime_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x70, 0x62, 0x2f,
	0x70, 0x72, 0x69, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x69,
	0x6d, 0x65, 0x22, 0x1f, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x22, 0x28, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x64, 0x69, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x64, 0x69, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x64, 0x73, 0x32, 0x40, 0x0a,
	0x0b, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x44, 0x69, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x64, 0x73, 0x12, 0x0c, 0x2e, 0x70,
	0x72, 0x69, 0x6d, 0x65, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x69,
	0x6d, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42,
	0x0f, 0x5a, 0x0d, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_prime_primepb_prime_proto_rawDescOnce sync.Once
	file_prime_primepb_prime_proto_rawDescData = file_prime_primepb_prime_proto_rawDesc
)

func file_prime_primepb_prime_proto_rawDescGZIP() []byte {
	file_prime_primepb_prime_proto_rawDescOnce.Do(func() {
		file_prime_primepb_prime_proto_rawDescData = protoimpl.X.CompressGZIP(file_prime_primepb_prime_proto_rawDescData)
	})
	return file_prime_primepb_prime_proto_rawDescData
}

var file_prime_primepb_prime_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_prime_primepb_prime_proto_goTypes = []interface{}{
	(*Prime)(nil),    // 0: prime.Prime
	(*Response)(nil), // 1: prime.Response
}
var file_prime_primepb_prime_proto_depIdxs = []int32{
	0, // 0: prime.PrimeServer.GetDividends:input_type -> prime.Prime
	1, // 1: prime.PrimeServer.GetDividends:output_type -> prime.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_prime_primepb_prime_proto_init() }
func file_prime_primepb_prime_proto_init() {
	if File_prime_primepb_prime_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_prime_primepb_prime_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Prime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prime_primepb_prime_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_prime_primepb_prime_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_prime_primepb_prime_proto_goTypes,
		DependencyIndexes: file_prime_primepb_prime_proto_depIdxs,
		MessageInfos:      file_prime_primepb_prime_proto_msgTypes,
	}.Build()
	File_prime_primepb_prime_proto = out.File
	file_prime_primepb_prime_proto_rawDesc = nil
	file_prime_primepb_prime_proto_goTypes = nil
	file_prime_primepb_prime_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PrimeServerClient is the client API for PrimeServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrimeServerClient interface {
	GetDividends(ctx context.Context, in *Prime, opts ...grpc.CallOption) (PrimeServer_GetDividendsClient, error)
}

type primeServerClient struct {
	cc grpc.ClientConnInterface
}

func NewPrimeServerClient(cc grpc.ClientConnInterface) PrimeServerClient {
	return &primeServerClient{cc}
}

func (c *primeServerClient) GetDividends(ctx context.Context, in *Prime, opts ...grpc.CallOption) (PrimeServer_GetDividendsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PrimeServer_serviceDesc.Streams[0], "/prime.PrimeServer/GetDividends", opts...)
	if err != nil {
		return nil, err
	}
	x := &primeServerGetDividendsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PrimeServer_GetDividendsClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type primeServerGetDividendsClient struct {
	grpc.ClientStream
}

func (x *primeServerGetDividendsClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PrimeServerServer is the server API for PrimeServer service.
type PrimeServerServer interface {
	GetDividends(*Prime, PrimeServer_GetDividendsServer) error
}

// UnimplementedPrimeServerServer can be embedded to have forward compatible implementations.
type UnimplementedPrimeServerServer struct {
}

func (*UnimplementedPrimeServerServer) GetDividends(*Prime, PrimeServer_GetDividendsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetDividends not implemented")
}

func RegisterPrimeServerServer(s *grpc.Server, srv PrimeServerServer) {
	s.RegisterService(&_PrimeServer_serviceDesc, srv)
}

func _PrimeServer_GetDividends_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Prime)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PrimeServerServer).GetDividends(m, &primeServerGetDividendsServer{stream})
}

type PrimeServer_GetDividendsServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type primeServerGetDividendsServer struct {
	grpc.ServerStream
}

func (x *primeServerGetDividendsServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

var _PrimeServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "prime.PrimeServer",
	HandlerType: (*PrimeServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetDividends",
			Handler:       _PrimeServer_GetDividends_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "prime/primepb/prime.proto",
}
